//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaViewer.MediaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class BaseMetadata
    {
        public BaseMetadata()
        {
            this.SupportsXMPMetadata = true;
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string Location { get; set; }
        public string Title { get; set; }
        public Nullable<double> Rating { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public string Copyright { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> MetadataModifiedDate { get; set; }
        public Nullable<System.DateTime> MetadataDate { get; set; }
        public string MimeType { get; set; }
        public long SizeBytes { get; set; }
        public string Software { get; set; }
        public bool SupportsXMPMetadata { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public System.DateTime FileDate { get; set; }
        public Nullable<int> ThumbnailId { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual Thumbnail Thumbnail { get; set; }
    }
}
