//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaViewer.MediaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageMetadata : BaseMetadata
    {
        public int Width { get; set; }
        public int Height { get; set; }
        public Nullable<short> LightSource { get; set; }
        public Nullable<short> MeteringMode { get; set; }
        public Nullable<short> Saturation { get; set; }
        public Nullable<short> SceneCaptureType { get; set; }
        public Nullable<short> SensingMethod { get; set; }
        public Nullable<short> Sharpness { get; set; }
        public Nullable<double> SubjectDistance { get; set; }
        public Nullable<double> ShutterSpeedValue { get; set; }
        public Nullable<short> SubjectDistanceRange { get; set; }
        public Nullable<short> WhiteBalance { get; set; }
        public Nullable<bool> FlashFired { get; set; }
        public Nullable<short> FlashMode { get; set; }
        public Nullable<short> FlashReturn { get; set; }
        public string CameraMake { get; set; }
        public string CameraModel { get; set; }
        public string Lens { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<double> ExposureTime { get; set; }
        public Nullable<double> FNumber { get; set; }
        public Nullable<double> ExposureBiasValue { get; set; }
        public Nullable<short> ExposureProgram { get; set; }
        public Nullable<double> FocalLength { get; set; }
        public Nullable<int> ISOSpeedRating { get; set; }
        public Nullable<short> Contrast { get; set; }
        public Nullable<short> Orientation { get; set; }
        public string PixelFormat { get; set; }
        public short BitsPerPixel { get; set; }
    }
}
