//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaViewer.MediaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public Media()
        {
            this.Tags = new HashSet<Tag>();
            this.VideoProps = new VideoProps();
            this.ImageProps = new ImageProps();
        }
    
        public int Id { get; set; }
        public string Location { get; set; }
        public string Title { get; set; }
        public Nullable<double> Rating { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public string Copyright { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string MimeType { get; set; }
        public long SizeBytes { get; set; }
    
        public VideoProps VideoProps { get; set; }
        public ImageProps ImageProps { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual Thumbnail Thumbnail { get; set; }
    }
}
