//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaViewer.MediaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.LinkedTags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TagCategoryId { get; set; }
        public Nullable<int> ParentTagId { get; set; }
    
        public virtual TagCategory TagCategory { get; set; }
        public virtual ICollection<Tag> LinkedTags { get; set; }
        public virtual Tag ParentTag { get; set; }
    }
}
