//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaViewer.MediaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thumbnail
    {
        public int Id { get; set; }
        public byte[] ImageData { get; set; }
        public short Width { get; set; }
        public short Height { get; set; }
        public Nullable<double> TimeSeconds { get; set; }
        public int BaseMetadataId { get; set; }
    
        public virtual BaseMetadata BaseMetadata { get; set; }
    }
}
