//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaViewer.MediaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoMedia : Media
    {
        public int Width { get; set; }
        public int Height { get; set; }
        public Nullable<short> BitsPerSample { get; set; }
        public int DurationSeconds { get; set; }
        public double FramesPerSecond { get; set; }
        public Nullable<short> NrChannels { get; set; }
        public string PixelFormat { get; set; }
        public Nullable<int> SamplesPerSecond { get; set; }
        public string VideoCodec { get; set; }
        public string VideoContainer { get; set; }
        public string AudioCodec { get; set; }
    }
}
