//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaViewer.MediaDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoMetadata : BaseMetadata
    {
        public VideoMetadata()
        {
            this.VideoThumbnails = new HashSet<VideoThumbnail>();
        }
    
        public int Width { get; set; }
        public int Height { get; set; }
        public Nullable<short> BitsPerSample { get; set; }
        public int DurationSeconds { get; set; }
        public double FramesPerSecond { get; set; }
        public Nullable<short> NrChannels { get; set; }
        public string PixelFormat { get; set; }
        public Nullable<int> SamplesPerSecond { get; set; }
        public string VideoCodec { get; set; }
        public string VideoContainer { get; set; }
        public string AudioCodec { get; set; }
        public string MajorBrand { get; set; }
        public Nullable<int> MinorVersion { get; set; }
        public Nullable<bool> IsVariableBitRate { get; set; }
        public string WMFSDKVersion { get; set; }
        public Nullable<short> BitsPerPixel { get; set; }
    
        public virtual ICollection<VideoThumbnail> VideoThumbnails { get; set; }
    }
}
