//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaViewer.MediaDatabase
{
    using System;
    
    public partial class VideoProps
    {
        public string VideoContainer { get; set; }
        public string VideoCodec { get; set; }
        public Nullable<long> Width { get; set; }
        public Nullable<long> Height { get; set; }
        public Nullable<long> DurationSeconds { get; set; }
        public string PixelFormat { get; set; }
        public Nullable<double> FramesPerSecond { get; set; }
        public Nullable<short> SamplesPerSecond { get; set; }
        public Nullable<short> NrChannels { get; set; }
        public Nullable<short> BitsPerSample { get; set; }
    }
}
